defaults:
  - model: model_conf
  - data: wmdp_cyber
  - eval: wmdp_cyber+mmlu
  - trainer: custom
  - hydra: default
  - paths: default
  - collator: DataCollatorForSupervisedDataset
  - _self_

mode: unlearn
task_name: wmdp_cyber_qwen
