# Inherit default args from configs/trainer/default.yaml
defaults:
  - default

# Overrides general (FinetuneTrainer) args
args:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  learning_rate: 5e-5
  lr_scheduler_type: constant
  eval_strategy: "no"
  eval_steps: 0.5
  max_steps: 80
  num_train_epochs: 10
  optim: paged_adamw_32bit
  weight_decay: 0.00
  seed: 0
  disable_tqdm: True

# Method-specific (CustomUnlearnTrainer) args
# method_args:
  # optional_arg: 1.0
