train_task_id: [Kinetix/Small, Minigrid]
test_task_id: [Kinetix/Medium, Kinetix/Large]
source_path: task_src/UnsupervisedEnvironmentDesign_all
template_backend: default
change_sample_levels: true
change_train_step: true
change_variable_config: true
