train_task_id: [muse, tofu, wmdp_cyber]
test_task_id: [muse, tofu, wmdp_cyber]

train_model_id: [Qwen2.5-1.5B-Instruct]
test_model_id: [Qwen2.5-1.5B-Instruct]

source_path: task_src/ModelUnlearning

change_loss: false
