repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [ '--maxkb=1024' ]
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: ^.devcontainer/devcontainer.json
      - id: pretty-format-json
        exclude: ^.devcontainer/devcontainer.json
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-executables-have-shebangs

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.2"
    hooks:
      - id: ruff
        exclude: ^discobench/tasks
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
        exclude: ^discobench/tasks

  - repo: local
    hooks:
      - id: mypy
        exclude: ^discobench/tasks
        name: mypy
        entry: uv run mypy
        language: python
        types: [ python ]
        require_serial: true
        verbose: true
