train_task_id: [LibriBrainSherlock1,LibriBrainSherlock2,LibriBrainSherlock3,LibriBrainSherlock4,LibriBrainSherlock5,LibriBrainSherlock6,LibriBrainSherlock7]
test_task_id: [LibriBrainSherlock1,LibriBrainSherlock2,LibriBrainSherlock3,LibriBrainSherlock4,LibriBrainSherlock5,LibriBrainSherlock6,LibriBrainSherlock7]

source_path: task_src/BrainSpeechDetection

change_optim: false
change_loss: false
change_networks: false
