# TODO: env_specific_config.py is listed 3 times is this intentional for some reason?
fixed_files:
  - __init__.py
  - config.py
  - env_specific_config.py
  - eval_utils.py
  - sfl_types.py
  - utils.py
  - env_specific_config.py
  - main.py
  - make_network.py
  - make_env.py
  - env_specific_config.py

module_files:
  - sample_levels.py
  - train_step.py
  - variable_config.py
