train_task_id: [OPCFineWebCode, OPCFineWebMath, LMFineWeb, TinyStories]
test_task_id: [OPCFineWebCode, OPCFineWebMath, LMFineWeb, TinyStories]

source_path: task_src/LanguageModelling

change_optim: false
change_loss: false
change_networks: false
