# Inherit default args from configs/trainer/default.yaml
defaults:
  - default

# Overrides general (FinetuneTrainer) args
args:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 1e-5
  num_train_epochs: 10
  lr_scheduler_type: constant
  optim: paged_adamw_32bit
  weight_decay: 0.0
  seed: 0
  disable_tqdm: True

# Method-specific (CustomUnlearnTrainer) args
# method_args:
  # optional_arg: 1.0
