train_task_id: [Kinetix/Small, Minigrid]
test_task_id: [Kinetix/Medium, Kinetix/Large]
source_path: task_src/UnsupervisedEnvironmentDesign_sample_levels
template_backend: default
change_sample_levels: true
change_train_step: false
change_variable_config: false
