# Inherit default args from configs/trainer/default.yaml
defaults:
  - default

# Overrides general (FinetuneTrainer) args
args:
  warmup_epochs: 1.0
  learning_rate: 1e-5
  num_train_epochs: 10
  optim: paged_adamw_32bit
  weight_decay: 0.01
  seed: 0
  disable_tqdm: True

# Method-specific (CustomUnlearnTrainer) args
# method_args:
  # optional_arg: 1.0
