train_task_id: [Kinetix/Small, Kinetix/Medium, Kinetix/Large, Minigrid]
test_task_id: [Kinetix/Small, Kinetix/Medium, Kinetix/Large, Minigrid]

source_path: task_src/UnsupervisedEnvironmentDesign

change_sample_levels: false
change_train_step: false
change_train_loop: false
change_config: false
