train_task_id: [CIFAR10C, CIFAR10, CIFAR10LT, CIFAR100, FashionMNIST, MNIST, OxfordFlowers, StandfordCars, TinyImageNet]
test_task_id: [CIFAR10C, CIFAR10, CIFAR10LT, CIFAR100, FashionMNIST, MNIST, OxfordFlowers, StandfordCars, TinyImageNet]

source_path: task_src/ComputerVisionClassification

change_optim: false
change_loss: false
change_networks: false
change_preprocess: false
