defaults:
  - model: model_conf
  - data: muse
  - eval: muse
  - trainer: custom
  - collator: DataCollatorForSupervisedDataset
  - hydra: default
  - paths: default
  - _self_

mode: unlearn
task_name: muse

# Alex: I think this can all be commented out because it just copies what is already specified in defaults:data:muse and defaults:eval:muse above.

# data_split: News
# forget_split: forget
# retain_split: retain1
# retain_logs_path: null

# data:
#   anchor: forget
#   forget:
#     MUSE_forget:
#       args:
#         hf_args:
#           split: ${forget_split}
#           path: muse-bench/MUSE-${data_split}
#   retain:
#     MUSE_retain:
#       args:
#         hf_args:
#           path: muse-bench/MUSE-${data_split}
#           split: ${retain_split}


# eval:
#   muse:
#     data_split: ${data_split}
#     retain_logs_path: ${retain_logs_path}
#     overwrite: true
