return_mean:
  default:
    Brax/Humanoid: 6130.256836
    Brax/Pusher: -392.628418
    Brax/Reacher: -76.182564
    Brax/Walker2D: 1043.490356
    MinAtar/Asterix: 15.96875
    MinAtar/Breakout: 61.078125
    MinAtar/Freeway: 62.171875
    MinAtar/SpaceInvaders: 182.125
  objective: max
  recurrent:
    MinAtar/Asterix: 15.96875
    MinAtar/Breakout: 61.078125
    MinAtar/Freeway: 61.953125
    MinAtar/SpaceInvaders: 182.125
  transformer:
    Brax/Humanoid: 6130.256836
    Brax/Pusher: -392.628418
    Brax/Reacher: -76.182564
    Brax/Walker2D: 1043.490356
    MinAtar/Asterix: 15.96875
    MinAtar/Breakout: 61.078125
    MinAtar/Freeway: 61.953125
    MinAtar/SpaceInvaders: 182.125
