train_task_id: [PermutedMNIST, SplitCIFAR100, TinyImageNetSplit]
test_task_id: [PermutedMNIST, SplitCIFAR100, TinyImageNetSplit]

source_path: task_src
template_backend: default  # default, parameter_isolation, transformer

change_regularizer: false
change_replay: false
change_sampler: false
change_scheduler: false
